import {
  DeleteOutlined,
  MailOutlined,
  PlusOutlined,
  ReloadOutlined,
} from "@ant-design/icons";
import {
  Button,
  Card,
  Col,
  Form,
  Input,
  Row,
  Select,
  Space,
  Table,
  Tag,
  Typography,
  message,
  Modal,
} from "antd";
import type { ColumnsType } from "antd/es/table";
import { useEffect, useMemo, useState } from "react";

import { api } from "@/lib/api";
import type { Conference, EmailDraft } from "@/types/conference";

interface ItemResponse<T> {
  items: T[];
}

const toneOptions = [
  "Concise, friendly, professional, direct, action-oriented",
  "Formal and executive",
  "Warm reminder",
  "Escalation-ready but polite",
];

const splitList = (value?: string) =>
  (value ?? "")
    .split(/[,\n;]/)
    .map((item) => item.trim())
    .filter(Boolean);

export default function EmailDrafts() {
  const [form] = Form.useForm();
  const [drafts, setDrafts] = useState<EmailDraft[]>([]);
  const [conferences, setConferences] = useState<Conference[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [deleteId, setDeleteId] = useState<string | null>(null);

  const conferenceOptions = useMemo(
    () =>
      conferences.map((conference) => ({
        value: conference.id,
        label: `${conference.conference_number || "No record"} / ${conference.acronym} ${conference.year} - ${conference.official_title}`,
      })),
    [conferences],
  );

  const fetchData = () => {
    setLoading(true);
    Promise.all([
      api<ItemResponse<EmailDraft>>("/email-drafts"),
      api<ItemResponse<Conference>>("/conferences"),
    ])
      .then(([draftData, conferenceData]) => {
        setDrafts(draftData.items ?? []);
        setConferences(conferenceData.items ?? []);
      })
      .catch((err) => message.error(err instanceof Error ? err.message : "Failed to load email drafts"))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchData();
  }, []);

  const generateDraft = async () => {
    const values = await form.validateFields();
    setGenerating(true);
    try {
      await api<EmailDraft>("/email-drafts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          conference_id: values.conference_id,
          issue_ids: [],
          recipient_names: splitList(values.recipient_names),
          recipient_addresses: splitList(values.recipient_addresses),
          cc_addresses: splitList(values.cc_addresses),
          purpose: values.purpose,
          instructions: values.instructions,
          tone: values.tone,
        }),
      });
      message.success("Draft generated");
      form.resetFields();
      fetchData();
    } catch (err) {
      message.error(err instanceof Error ? err.message : "Draft generation failed");
    } finally {
      setGenerating(false);
    }
  };

  const handleDelete = async () => {
    if (!deleteId) return;
    try {
      await api(`/email-drafts/${deleteId}`, { method: "DELETE" });
      message.success("Draft deleted");
      setDeleteId(null);
      fetchData();
    } catch (err) {
      message.error(err instanceof Error ? err.message : "Delete failed");
    }
  };

  const columns: ColumnsType<EmailDraft> = [
    {
      title: "Subject",
      dataIndex: "subject",
      width: 340,
      sorter: (a, b) => a.subject.localeCompare(b.subject),
      render: (value: string, record) => (
        <Space direction="vertical" size={0}>
          <Typography.Text strong className="table-title"><MailOutlined /> {value}</Typography.Text>
          <Typography.Text type="secondary">
            Generated by {record.generator || "Local composer"}
          </Typography.Text>
        </Space>
      ),
    },
    {
      title: "Conference",
      key: "conference",
      width: 140,
      render: (_, record) =>
        record.conference_acronym ? `${record.conference_acronym} ${record.conference_year ?? ""}` : "-",
    },
    {
      title: "To",
      dataIndex: "recipient_addresses",
      width: 220,
      ellipsis: true,
      render: (value: string | null) => value || "-",
    },
    {
      title: "Tone",
      dataIndex: "tone",
      width: 220,
      ellipsis: true,
      render: (value: string | null) => <Tag>{value || "Professional"}</Tag>,
    },
    {
      title: "Created",
      dataIndex: "created_at",
      width: 130,
      sorter: (a, b) => a.created_at.localeCompare(b.created_at),
      render: (value: string) => new Date(value).toLocaleDateString(),
    },
    {
      title: "Actions",
      key: "actions",
      width: 80,
      render: (_, record) => (
        <Button danger size="small" icon={<DeleteOutlined />} onClick={() => setDeleteId(record.id)} />
      ),
    },
  ];

  return (
    <div>
      <div className="page-header">
        <div>
          <Typography.Text className="hero-kicker">Generated communication</Typography.Text>
          <h1>Email Drafts</h1>
          <Typography.Text type="secondary">
            Generate conference-specific messages with recipients, CC, tone, and editable instructions.
          </Typography.Text>
        </div>
        <Button icon={<ReloadOutlined />} onClick={fetchData}>
          Refresh
        </Button>
      </div>

      <Row gutter={[16, 16]}>
        <Col xs={24} lg={8}>
          <Card title={<><PlusOutlined /> Generate Draft</>}>
            <Form
              form={form}
              layout="vertical"
              initialValues={{
                purpose: "Request status update",
                tone: toneOptions[0],
              }}
            >
              <Form.Item
                name="conference_id"
                label="Conference"
                rules={[{ required: true, message: "Select a conference" }]}
              >
                <Select
                  showSearch
                  options={conferenceOptions}
                  optionFilterProp="label"
                  placeholder="Record number / abbreviation"
                />
              </Form.Item>
              <Form.Item name="recipient_names" label="Recipient Names">
                <Input.TextArea rows={2} placeholder="One or more names, separated by comma or newline" />
              </Form.Item>
              <Form.Item name="recipient_addresses" label="To">
                <Input.TextArea rows={2} placeholder="email@example.org, another@example.org" />
              </Form.Item>
              <Form.Item name="cc_addresses" label="CC">
                <Input.TextArea rows={2} placeholder="Optional CC list" />
              </Form.Item>
              <Form.Item name="tone" label="Tone">
                <Select options={toneOptions.map((value) => ({ label: value, value }))} />
              </Form.Item>
              <Form.Item name="purpose" label="Purpose" rules={[{ required: true }]}>
                <Input placeholder="Request status update" />
              </Form.Item>
              <Form.Item name="instructions" label="Optional Instructions">
                <Input.TextArea rows={4} placeholder="Add specific points the draft should cover" />
              </Form.Item>
              <Button type="primary" icon={<MailOutlined />} loading={generating} onClick={generateDraft} block>
                Generate Draft
              </Button>
            </Form>
          </Card>
        </Col>

        <Col xs={24} lg={16}>
          <Card title="Draft Library">
            <Table
              dataSource={drafts}
              columns={columns}
              rowKey="id"
              loading={loading}
              pagination={{ pageSize: 6, showTotal: (total) => `${total} drafts` }}
              expandable={{
                expandedRowRender: (record) => <pre className="draft-body">{record.body}</pre>,
              }}
              scroll={{ x: 1130 }}
            />
          </Card>
        </Col>
      </Row>

      <Modal
        title="Delete Draft"
        open={deleteId !== null}
        onOk={handleDelete}
        onCancel={() => setDeleteId(null)}
        okText="Delete"
        okButtonProps={{ danger: true }}
      >
        <p>This deletes the saved draft only.</p>
      </Modal>
    </div>
  );
}
